version: '3.3'

services:
  simplefin-notifier:
    image: ghcr.io/thiagogpa/simplefin-notifier:latest
    container_name: simplefin-notifier
    # build:
    #   context: .
    #   dockerfile: Dockerfile    
    environment:
      - CREDENTIALS_PATH=/app/credentials
      - FILE_LOGGING_LEVEL=INFO
      - SIMPLEFIN_BRIDGE_TOKEN=${SIMPLEFIN_BRIDGE_TOKEN}
      - GOTIFY_BASE_URL=${GOTIFY_BASE_URL}
      - GOTIFY_APP_TOKEN=${GOTIFY_APP_TOKEN}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - CRON_SCHEDULE=0 12 * * *              # Change the schedule as needed
    volumes:
      - ./credentials:/app/credentials
      - ./.env:/app/.env
    restart: unless-stopped
